version: '3'
services:
  app:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - ./src/config/config.env  # Ensure this path is correct
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
